In [14]:
import numpy as np
x = int(input("no of rows:"))
y = int(input("no of coloumn:"))

entries = list(map(int, input().split()))
m1 = np.array(entries).reshape(x,y)
print("Matirix 1 \n",m1)


a = int(input("no of rows:"))
b = int(input("no of coloumn:"))

entries = list(map(int, input().split()))
m2 = np.array(entries).reshape(a,b)
print("Matrix 2 \n",m2)

print("\n dot product \n",np.dot(m1,m2))

no of rows: 2
no of coloumn: 2
 4 5 6 7


Matirix 1 
 [[4 5]
 [6 7]]


no of rows: 2
no of coloumn: 2
 6 5 3 6


Matrix 2 
 [[6 5]
 [3 6]]
/n dot product /n [[39 50]
 [57 72]]


In [15]:
#2
print("Transpose of matrix_1: \n",matrix_1.transpose(), "\n Transpose of matrix_2: \n",matrix_2.transpose())

Transpose of matrix_1: 
 [[5 7]
 [6 8]] 
 Transpose of matrix_2: 
 [[5 7]
 [6 8]]


In [16]:


 #trace
    
print("Trace of matrix_1: \n",np.trace(matrix_1),"\n Trace of matrix_2: \n",np.trace(matrix_2))    



Trace of matrix_1: 
 13 
 Trace of matrix_2: 
 13


In [17]:
#rank

print("The rank of matrix_1 :",np.linalg.matrix_rank(matrix_1),"\n The rank of matrix_2 :",np.linalg.matrix_rank(matrix_2))

The rank of matrix_1 : 2 
 The rank of matrix_2 : 2


In [18]:


#determinent

print("The determinent of matrix_1 :",int(np.linalg.det(matrix_1)),"\n The determinent of matrix_2 :",int(np.linalg.det(matrix_2)))



The determinent of matrix_1 : -1 
 The determinent of matrix_2 : -1


In [20]:
#Inverse

print("The inverse of matrix_1 : \n",np.linalg.inv(matrix_1),"\n The inverse of matrix_2 : \n",np.linalg.inv(matrix_2))


The inverse of matrix_1 : 
 [[-4.   3. ]
 [ 3.5 -2.5]] 
 The inverse of matrix_2 : 
 [[-4.   3. ]
 [ 3.5 -2.5]]
The eigen values of matrix_1 : 
 [-0.15206735 13.15206735]
 The eigen vectors of matrix_1:
 [[-0.75868086 -0.59276441]
 [ 0.65146248 -0.80537591]]
The eigen values of matrix_2 : 
 [-0.15206735 13.15206735]
 The eigen vectors of matrix_2:
 [[-0.75868086 -0.59276441]
 [ 0.65146248 -0.80537591]]


In [21]:
#Eigen values and eigen vectors

w1, v1 = np.linalg.eig(matrix_1)


print("The eigen values of matrix_1 : \n",w1)
print(" The eigen vectors of matrix_1:\n",v1)

w2 , v2 = np.linalg.eig(matrix_2)

print("The eigen values of matrix_2 : \n",w2)
print(" The eigen vectors of matrix_2:\n",v2)

The eigen values of matrix_1 : 
 [-0.15206735 13.15206735]
 The eigen vectors of matrix_1:
 [[-0.75868086 -0.59276441]
 [ 0.65146248 -0.80537591]]
The eigen values of matrix_2 : 
 [-0.15206735 13.15206735]
 The eigen vectors of matrix_2:
 [[-0.75868086 -0.59276441]
 [ 0.65146248 -0.80537591]]
